### ISSUE TITLE
Abstract data away from the teensy

### ISSUE THREAD

**Issue by Soups71** [thedini/openBridge#7]
The end goal is to be able to send NMEA2000 data from the computer for any device and then send it to the teensy to actually interface with the NMEA2000 bus. This would allow for greater flexibility with the teensy instead of having to flash new firmware on to the device.

**Comment by Soups71** [comment]
This is accomplished in the branch labeled VERSION_2. In this revision the Teensy is able to be flashed once. Then the computer code can be tweaked in order to send different values to the teensy. @thedini Please add comments as to what you hope to see in further revisions.

**Comment by thedini** [comment]
@Soups71 is it time to bring this back?
